package com.osi.ems.domain;
// Generated Dec 11, 2017 1:01:32 PM by Hibernate Tools 5.2.3.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * OsiBusinessUnits generated by hbm2java
 */
@Entity
@Table(name = "osi_business_units")
public class OsiBusinessUnits implements java.io.Serializable {

	private String buShortName;
	private Integer buId;
	private String buLongName;
	private Integer active;
	private Integer createdBy;
	private Date creationDate;
	private Integer lastUpdatedBy;
	private Date lastUpdateDate;

	public OsiBusinessUnits() {
	}


	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "BU_ID", unique = true, nullable = false)
	public Integer getBuId() {
		return this.buId;
	}

	public void setBuId(Integer buId) {
		this.buId = buId;
	}

	@Column(name = "BU_SHORT_NAME", unique = true, nullable = false, length = 45)
	public String getBuShortName() {
		return this.buShortName;
	}

	public void setBuShortName(String buShortName) {
		this.buShortName = buShortName;
	}

	@Column(name = "BU_LONG_NAME", length = 512)
	public String getBuLongName() {
		return this.buLongName;
	}

	public void setBuLongName(String buLongName) {
		this.buLongName = buLongName;
	}

	@Column(name = "ACTIVE", nullable = false)
	public Integer getActive() {
		return this.active;
	}

	public void setActive(Integer active) {
		this.active = active;
	}

	@Column(name = "CREATED_BY", nullable = false,updatable = false)
	public Integer getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(Integer createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATION_DATE", nullable = false, length = 19,updatable = false)
	public Date getCreationDate() {
		return this.creationDate;
	}

	public void setCreationDate(Date creationDate) {
		this.creationDate = creationDate;
	}

	@Column(name = "LAST_UPDATED_BY", nullable = false)
	public Integer getLastUpdatedBy() {
		return this.lastUpdatedBy;
	}

	public void setLastUpdatedBy(Integer lastUpdatedBy) {
		this.lastUpdatedBy = lastUpdatedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LAST_UPDATE_DATE", nullable = false, length = 19)
	public Date getLastUpdateDate() {
		return this.lastUpdateDate;
	}

	public void setLastUpdateDate(Date lastUpdateDate) {
		this.lastUpdateDate = lastUpdateDate;
	}

}
