

package com.osi.ems.domain;

//Generated Dec 1, 2016 5:20:37 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;


/**
* OsiCategorys generated by hbm2java
*/
@Entity
@Table(name = "osi_categories")
public class OsiCategories implements java.io.Serializable {


	/**
	 * 
	 */
	private static final long serialVersionUID = 7240316386460887204L;
	private Integer id;
	private String catName;
	private String tblName;
	private String inlineOrPopup;
	
	private Integer createdBy;
	private Date createdDate;
	private Integer updatedBy;
	private Date updatedDate;
	//private OsiOrganizations OsiOrganizations;
	
	@Column(name ="org_id",nullable=false)
	private Integer orgId;
	private Integer active;

	private Set<OsiCategoryFields> osiCategoryFields = new HashSet<OsiCategoryFields>(
			0);
	
	

	public OsiCategories() {
	}



	public OsiCategories(Integer id, String catName, String tblName,Integer orgId,
		 Integer createdBy,
			Date createdDate, Integer updatedBy, Date updatedDate,
			Set<OsiCategoryFields> osiCategoryFields) {
		this.id = id;
		this.catName = catName;
		this.tblName = tblName;
		this.orgId= orgId;
		this.createdBy = createdBy;
		this.createdDate = createdDate;
		this.updatedBy = updatedBy;
		this.updatedDate = updatedDate;
		this.osiCategoryFields = osiCategoryFields;
		
	}

	@Id
	@Column(name = "category_id", unique = true, nullable = false)
	@GeneratedValue(strategy=GenerationType.AUTO)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "category_name", nullable = false, length = 100)
	public String getCatName() {
		return catName;
	}

	public void setCatName(String catName) {
		this.catName = catName;
	}


	@Column(name = "table_name", nullable = false, length = 1000)

	public String getTblName() {
		return tblName;
	}



	public void setTblName(String tblName) {
		this.tblName = tblName;
	}

	public Integer getOrgId() {
		return orgId;
	}


	public void setOrgId(Integer orgId) {
		this.orgId = orgId;
	}

	@Column(name = "active")
	public Integer getActive() {
		return active;
	}

	public void setActive(Integer active) {
		this.active = active;
	}

	@Column(name = "created_by")
	public Integer getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(Integer createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "creation_date", length = 0)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Column(name = "last_updated_by")
	public Integer getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(Integer updatedBy) {
		this.updatedBy = updatedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "last_update_date", length = 0)
	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

	@OneToMany(mappedBy="osiCategory", cascade=CascadeType.ALL,fetch=FetchType.EAGER)
	public Set<OsiCategoryFields> getOsiCategoryFields() {
		return osiCategoryFields;
	}
	public void setOsiCategoryFields(Set<OsiCategoryFields> osiCategoryFields) {
		this.osiCategoryFields = osiCategoryFields;
	}


	@Column(name = "inline_popup")
	public String getInlineOrPopup() {
		return inlineOrPopup;
	}



	public void setInlineOrPopup(String inlineOrPopup) {
		this.inlineOrPopup = inlineOrPopup;
	}


}
