package com.osi.ems.domain;
//Generated Dec 8, 2017 2:18:30 PM by Hibernate Tools 5.2.3.Final

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

/**
* OsiCostCenter generated by hbm2java
*/
@Entity
@Table(name = "osi_emp_additional_docs")
public class OsiEmpAdditionalDocs implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private Integer docId;
	private Integer employeeId;
	private Integer attachmentId;
	private String description;

	public OsiEmpAdditionalDocs() {
	}

	
	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "doc_id", unique = true, nullable = false)
	public Integer getDocId() {
		return docId;
	}

	public void setDocId(Integer docId) {
		this.docId = docId;
	}

	@Column(name = "employee_id")
	public Integer getEmployeeId() {
		return employeeId;
	}

	public void setEmployeeId(Integer employeeId) {
		this.employeeId = employeeId;
	}

	@Column(name = "attachment_id")
	public Integer getAttachmentId() {
		return attachmentId;
	}

	public void setAttachmentId(Integer attachmentId) {
		this.attachmentId = attachmentId;
	}

	@Column(name = "description")
	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}
	
}
