package com.osi.ems.domain;
// Generated Nov 30, 2017 4:45:33 PM by Hibernate Tools 5.2.3.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * OsiRegions generated by hbm2java
 */
@Entity
@Table(name = "osi_regions")
public class OsiRegions implements java.io.Serializable {

	private String regionShortName;
	private int regionId;
	private String regionName;
	private int createdBy;
	private Date creationDate;
	private int lastUpdatedBy;
	private Date lastUpdateDate;
	private Set<OsiLocations> osiLocationsForRegionId = new HashSet<OsiLocations>(0);

	public OsiRegions() {
	}

	public OsiRegions(int regionId, String regionName, int createdBy, Date creationDate, int lastUpdatedBy,
			Date lastUpdateDate,Set<OsiLocations> osiLocationsForRegionId) {
		this.regionId = regionId;
		this.regionName = regionName;
		this.createdBy = createdBy;
		this.creationDate = creationDate;
		this.lastUpdatedBy = lastUpdatedBy;
		this.lastUpdateDate = lastUpdateDate;
		this.osiLocationsForRegionId=osiLocationsForRegionId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	
	@Column(name = "region_id", unique = true, nullable = false)
	public int getRegionId() {
		return this.regionId;
	}

	public void setRegionId(int regionId) {
		this.regionId = regionId;
	}

	@Column(name = "region_short_name", unique = true, nullable = false, length = 45)
	public String getRegionShortName() {
		return this.regionShortName;
	}

	public void setRegionShortName(String regionShortName) {
		this.regionShortName = regionShortName;
	}


	@Column(name = "region_name", nullable = false, length = 512)
	public String getRegionName() {
		return this.regionName;
	}

	public void setRegionName(String regionName) {
		this.regionName = regionName;
	}

	@Column(name = "CREATED_BY", nullable = false)
	public int getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(int createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATION_DATE", nullable = false, length = 19)
	public Date getCreationDate() {
		return this.creationDate;
	}

	public void setCreationDate(Date creationDate) {
		this.creationDate = creationDate;
	}

	@Column(name = "LAST_UPDATED_BY", nullable = false)
	public int getLastUpdatedBy() {
		return this.lastUpdatedBy;
	}

	public void setLastUpdatedBy(int lastUpdatedBy) {
		this.lastUpdatedBy = lastUpdatedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LAST_UPDATE_DATE", nullable = false, length = 19)
	public Date getLastUpdateDate() {
		return this.lastUpdateDate;
	}

	public void setLastUpdateDate(Date lastUpdateDate) {
		this.lastUpdateDate = lastUpdateDate;
	}
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "osiRegionsId")
	public Set<OsiLocations> getOsiLocationsForRegionId() {
		return osiLocationsForRegionId;
	}

	public void setOsiLocationsForRegionId(Set<OsiLocations> osiLocationsForRegionId) {
		this.osiLocationsForRegionId = osiLocationsForRegionId;
	}

}
