package com.osi.ems.domain;
// Generated Dec 5, 2017 4:13:09 PM by Hibernate Tools 5.2.3.Final

import java.util.Date;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * OsiTitleGradesId generated by hbm2java
 */
@Entity
@Table(name = "osi_title_grades")
public class OsiTitleGrades implements java.io.Serializable {

	private Integer titleGradeId;
	private Integer titleId;
	private OsiGrades gradeId;
	private Integer createdBy;
	private Date creationDate;
	private Integer lastUpdatedBy;
	private Date lastUpdateDate;

	public OsiTitleGrades(Integer titleGradeId, Integer titleId, OsiGrades grades, Integer createdBy,
			Date creationDate, Integer lastUpdatedBy, Date lastUpdateDate) {

		this.titleGradeId = titleGradeId;
		this.titleId = titleId;
		this.gradeId = grades;
		this.createdBy = createdBy;
		this.creationDate = creationDate;
		this.lastUpdatedBy = lastUpdatedBy;
		this.lastUpdateDate = lastUpdateDate;
	}



	public OsiTitleGrades() {
	}
	


	@Id
	@GeneratedValue(strategy=GenerationType.AUTO)
	@Column(name = "TITLE_GRADE_ID", unique = true, nullable = false)
	public Integer getTitleGradeId() {
		return this.titleGradeId;
	}

	public void setTitleGradeId(Integer titleGradeId) {
		this.titleGradeId = titleGradeId;
	}

	@Column(name = "TITLE_ID", nullable = false)
	public Integer getTitleId() {
		return this.titleId;
	}

	public void setTitleId(Integer titleId) {
		this.titleId = titleId;
	}


	@JoinColumn(name = "grade_id")
	@ManyToOne(cascade = CascadeType.ALL)
	public OsiGrades getGrades() {
		return gradeId;
	}



	public void setGrades(OsiGrades grades) {
		this.gradeId = grades;
	}



	@Column(name = "CREATED_BY", nullable = false,updatable = false)
	public Integer getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(Integer createdBy) {
		this.createdBy = createdBy;
	}

	@Column(name = "CREATION_DATE", nullable = false, length = 19,updatable = false)
	public Date getCreationDate() {
		return this.creationDate;
	}

	public void setCreationDate(Date creationDate) {
		this.creationDate = creationDate;
	}

	@Column(name = "LAST_UPDATED_BY", nullable = false)
	public Integer getLastUpdatedBy() {
		return this.lastUpdatedBy;
	}

	public void setLastUpdatedBy(Integer lastUpdatedBy) {
		this.lastUpdatedBy = lastUpdatedBy;
	}

	@Column(name = "LAST_UPDATE_DATE", nullable = false, length = 19)
	public Date getLastUpdateDate() {
		return this.lastUpdateDate;
	}

	public void setLastUpdateDate(Date lastUpdateDate) {
		this.lastUpdateDate = lastUpdateDate;
	}

}
