package com.osi.urm.domain;

// Generated Mar 3, 2017 8:07:44 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * OsiListValues generated by hbm2java
 */
@Entity
@Table(name = "osi_list_values")
public class OsiListValues implements java.io.Serializable {

	private int listValuesId;
	private Integer listId;
	private String listValue;
	private Integer listSeq;
	private Integer createdBy;
	private Date creationDate;
	private Integer lastUpdatedBy;
	private Date lastUpdateDate;

	public OsiListValues() {
	}

	public OsiListValues(int listValuesId) {
		this.listValuesId = listValuesId;
	}

	public OsiListValues(int listValuesId, Integer listId, String listValue,
			Integer listSeq, Integer createdBy, Date creationDate,
			Integer lastUpdatedBy, Date lastUpdateDate) {
		this.listValuesId = listValuesId;
		this.listId = listId;
		this.listValue = listValue;
		this.listSeq = listSeq;
		this.createdBy = createdBy;
		this.creationDate = creationDate;
		this.lastUpdatedBy = lastUpdatedBy;
		this.lastUpdateDate = lastUpdateDate;
	}

	@Id
	@Column(name = "LIST_VALUES_ID", unique = true, nullable = false)
	public int getListValuesId() {
		return this.listValuesId;
	}

	public void setListValuesId(int listValuesId) {
		this.listValuesId = listValuesId;
	}

	@Column(name = "LIST_ID")
	public Integer getListId() {
		return this.listId;
	}

	public void setListId(Integer listId) {
		this.listId = listId;
	}

	@Column(name = "LIST_VALUE")
	public String getListValue() {
		return this.listValue;
	}

	public void setListValue(String listValue) {
		this.listValue = listValue;
	}

	@Column(name = "LIST_SEQ")
	public Integer getListSeq() {
		return this.listSeq;
	}

	public void setListSeq(Integer listSeq) {
		this.listSeq = listSeq;
	}

	@Column(name = "CREATED_BY")
	public Integer getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(Integer createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "CREATION_DATE", length = 0)
	public Date getCreationDate() {
		return this.creationDate;
	}

	public void setCreationDate(Date creationDate) {
		this.creationDate = creationDate;
	}

	@Column(name = "LAST_UPDATED_BY")
	public Integer getLastUpdatedBy() {
		return this.lastUpdatedBy;
	}

	public void setLastUpdatedBy(Integer lastUpdatedBy) {
		this.lastUpdatedBy = lastUpdatedBy;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "LAST_UPDATE_DATE", length = 0)
	public Date getLastUpdateDate() {
		return this.lastUpdateDate;
	}

	public void setLastUpdateDate(Date lastUpdateDate) {
		this.lastUpdateDate = lastUpdateDate;
	}

}
