package com.osi.urm.domain;

// Generated Mar 3, 2017 8:07:44 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

/**
 * OsiRmRequests generated by hbm2java
 */
@Entity
@Table(name = "osi_rm_requests")
public class OsiRmRequests implements java.io.Serializable {

	private Integer requestId;
	private Integer reportId;
	private String requestProcess;
	private String requestStatus;
	private Date requestDate;
	private String requestSubmitionDate;
	private String requestSchedulEndDate;
	private Date actualExecStartTime;
	private Date actualExecEndTime;
	private Integer requestedBy;
	private byte[] requestArguments;
	private String requestArgumentsType;
	private Date creationDate;
	private String logFileName;
	private String outputFileName;
	private Integer isRepeat;
	private Integer repeatInterval;
	private Integer scheduleFrequencyId;
	private String hostName;
	private Integer processId;
	private Date reqestScheEndDate;
	private String outputType;
	private Integer parentRequestId;
	private Integer businessGroupId;
	private String startDate;
	private String endDate;
	private String scheduleStaus;
	private String duration;
	private String userName;
	private String reportName;
	private String isRepeatFlag;
	private String scheduleFrequency;
	private Integer rptGroupId;
	
	@Transient
	public Integer getRptGroupId() {
		return rptGroupId;
	}

	public void setRptGroupId(Integer rptGroupId) {
		this.rptGroupId = rptGroupId;
	}

	@Transient
	public String getIsRepeatFlag() {
		return isRepeatFlag;
	}

	public void setIsRepeatFlag(String isRepeatFlag) {
		this.isRepeatFlag = isRepeatFlag;
	}
	@Transient
	public String getScheduleFrequency() {
		return scheduleFrequency;
	}

	public void setScheduleFrequency(String scheduleFrequency) {
		this.scheduleFrequency = scheduleFrequency;
	}

	@Transient
	public String getUserName() {
		return userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}
	@Transient
	public String getReportName() {
		return reportName;
	}

	public void setReportName(String reportName) {
		this.reportName = reportName;
	}

	@Transient
	public String getStartDate() {
		return startDate;
	}

	public void setStartDate(String startDate) {
		this.startDate = startDate;
	}
	@Transient
	public String getEndDate() {
		return endDate;
	}

	public void setEndDate(String endDate) {
		this.endDate = endDate;
	}
	@Transient
	public String getScheduleStaus() {
		return scheduleStaus;
	}
	@Transient
	public String getDuration() {
		return duration;
	}

	public void setDuration(String duration) {
		this.duration = duration;
	}

	public void setScheduleStaus(String scheduleStaus) {
		this.scheduleStaus = scheduleStaus;
	}

	public OsiRmRequests() {
	}

	public OsiRmRequests(Integer requestId) {
		this.requestId = requestId;
	}

	public OsiRmRequests(Integer requestId, Integer reportId,
			String requestProcess, String requestStatus, Date requestDate,
			Date actualExecStartTime, Date actualExecEndTime,
			Integer requestedBy, byte[] requestArguments,
			String requestArgumentsType, Date creationDate, String logFileName,
			String outputFileName, Integer isRepeat, Integer repeatInterval,
			Integer scheduleFrequencyId, String hostName, Integer processId,
			Date reqestScheEndDate, String outputType, Integer parentRequestId) {
		this.requestId = requestId;
		this.reportId = reportId;
		this.requestProcess = requestProcess;
		this.requestStatus = requestStatus;
		this.requestDate = requestDate;
		this.actualExecStartTime = actualExecStartTime;
		this.actualExecEndTime = actualExecEndTime;
		this.requestedBy = requestedBy;
		this.requestArguments = requestArguments;
		this.requestArgumentsType = requestArgumentsType;
		this.creationDate = creationDate;
		this.logFileName = logFileName;
		this.outputFileName = outputFileName;
		this.isRepeat = isRepeat;
		this.repeatInterval = repeatInterval;
		this.scheduleFrequencyId = scheduleFrequencyId;
		this.hostName = hostName;
		this.processId = processId;
		this.reqestScheEndDate = reqestScheEndDate;
		this.outputType = outputType;
		this.parentRequestId = parentRequestId;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "REQUEST_ID", unique = true, nullable = false)
	public Integer getRequestId() {
		return this.requestId;
	}

	public void setRequestId(Integer requestId) {
		this.requestId = requestId;
	}

	@Column(name = "REPORT_ID")
	public Integer getReportId() {
		return this.reportId;
	}

	public void setReportId(Integer reportId) {
		this.reportId = reportId;
	}

	@Column(name = "REQUEST_PROCESS", length = 50)
	public String getRequestProcess() {
		return this.requestProcess;
	}

	public void setRequestProcess(String requestProcess) {
		this.requestProcess = requestProcess;
	}

	@Column(name = "REQUEST_STATUS", length = 50)
	public String getRequestStatus() {
		return this.requestStatus;
	}

	public void setRequestStatus(String requestStatus) {
		this.requestStatus = requestStatus;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "REQUEST_DATE", length = 0)
	public Date getRequestDate() {
		return this.requestDate;
	}

	public void setRequestDate(Date requestDate) {
		this.requestDate = requestDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ACTUAL_EXEC_START_TIME", length = 0)
	public Date getActualExecStartTime() {
		return this.actualExecStartTime;
	}

	public void setActualExecStartTime(Date actualExecStartTime) {
		this.actualExecStartTime = actualExecStartTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ACTUAL_EXEC_END_TIME", length = 0)
	public Date getActualExecEndTime() {
		return this.actualExecEndTime;
	}

	public void setActualExecEndTime(Date actualExecEndTime) {
		this.actualExecEndTime = actualExecEndTime;
	}

	@Column(name = "REQUESTED_BY")
	public Integer getRequestedBy() {
		return this.requestedBy;
	}

	public void setRequestedBy(Integer requestedBy) {
		this.requestedBy = requestedBy;
	}

	@Column(name = "REQUEST_ARGUMENTS")
	public byte[] getRequestArguments() {
		return this.requestArguments;
	}

	public void setRequestArguments(byte[] requestArguments) {
		this.requestArguments = requestArguments;
	}

	@Column(name = "REQUEST_ARGUMENTS_TYPE")
	public String getRequestArgumentsType() {
		return this.requestArgumentsType;
	}

	public void setRequestArgumentsType(String requestArgumentsType) {
		this.requestArgumentsType = requestArgumentsType;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATION_DATE", length = 0)
	public Date getCreationDate() {
		return this.creationDate;
	}

	public void setCreationDate(Date creationDate) {
		this.creationDate = creationDate;
	}

	@Column(name = "LOG_FILE_NAME")
	public String getLogFileName() {
		return this.logFileName;
	}

	public void setLogFileName(String logFileName) {
		this.logFileName = logFileName;
	}

	@Column(name = "OUTPUT_FILE_NAME")
	public String getOutputFileName() {
		return this.outputFileName;
	}

	public void setOutputFileName(String outputFileName) {
		this.outputFileName = outputFileName;
	}

	@Column(name = "IS_REPEAT")
	public Integer getIsRepeat() {
		return this.isRepeat;
	}

	public void setIsRepeat(Integer isRepeat) {
		this.isRepeat = isRepeat;
	}

	@Column(name = "REPEAT_INTERVAL")
	public Integer getRepeatInterval() {
		return this.repeatInterval;
	}

	public void setRepeatInterval(Integer repeatInterval) {
		this.repeatInterval = repeatInterval;
	}

	@Column(name = "SCHEDULE_FREQUENCY_ID")
	public Integer getScheduleFrequencyId() {
		return this.scheduleFrequencyId;
	}

	public void setScheduleFrequencyId(Integer scheduleFrequencyId) {
		this.scheduleFrequencyId = scheduleFrequencyId;
	}

	@Column(name = "HOST_NAME")
	public String getHostName() {
		return this.hostName;
	}

	public void setHostName(String hostName) {
		this.hostName = hostName;
	}

	@Column(name = "PROCESS_ID")
	public Integer getProcessId() {
		return this.processId;
	}

	public void setProcessId(Integer processId) {
		this.processId = processId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "REQEST_SCHE_END_DATE", length = 0)
	public Date getReqestScheEndDate() {
		return this.reqestScheEndDate;
	}

	public void setReqestScheEndDate(Date reqestScheEndDate) {
		this.reqestScheEndDate = reqestScheEndDate;
	}

	@Column(name = "OUTPUT_TYPE", length = 45)
	public String getOutputType() {
		return this.outputType;
	}

	public void setOutputType(String outputType) {
		this.outputType = outputType;
	}

	@Column(name = "PARENT_REQUEST_ID")
	public Integer getParentRequestId() {
		return this.parentRequestId;
	}

	public void setParentRequestId(Integer parentRequestId) {
		this.parentRequestId = parentRequestId;
	}
	@Column(name = "BUSINESS_GROUP_ID")
	public Integer getBusinessGroupId() {
		return businessGroupId;
	}

	public void setBusinessGroupId(Integer businessGroupId) {
		this.businessGroupId = businessGroupId;
	}
	@Transient
	public String getRequestSubmitionDate() {
		return requestSubmitionDate;
	}

	public void setRequestSubmitionDate(String requestSubmitionDate) {
		this.requestSubmitionDate = requestSubmitionDate;
	}
	@Transient
	public String getRequestSchedulEndDate() {
		return requestSchedulEndDate;
	}

	public void setRequestSchedulEndDate(String requestSchedulEndDate) {
		this.requestSchedulEndDate = requestSchedulEndDate;
	}
	
}
