package com.osi.urm.domain;

// Generated Mar 3, 2017 8:07:44 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * OsiReportArgs generated by hbm2java
 */
@Entity
@Table(name = "osi_report_args")
public class OsiReportArgs implements java.io.Serializable {

	private int reportArgsId;
	private Integer reportId;
	private Integer displaySeq;
	private String screenDisplayName;
	private String parameterName;
	private Integer listId;
	private String paramRequired;
	private String multiSelect;
	private Integer createdBy;
	private Date creationDate;
	private Integer lastUpdatedBy;
	private Date lastUpdateDate;

	public OsiReportArgs() {
	}

	public OsiReportArgs(int reportArgsId) {
		this.reportArgsId = reportArgsId;
	}

	public OsiReportArgs(int reportArgsId, Integer reportId,
			Integer displaySeq, String screenDisplayName, String parameterName,
			Integer listId, String paramRequired, String multiSelect,
			Integer createdBy, Date creationDate, Integer lastUpdatedBy,
			Date lastUpdateDate) {
		this.reportArgsId = reportArgsId;
		this.reportId = reportId;
		this.displaySeq = displaySeq;
		this.screenDisplayName = screenDisplayName;
		this.parameterName = parameterName;
		this.listId = listId;
		this.paramRequired = paramRequired;
		this.multiSelect = multiSelect;
		this.createdBy = createdBy;
		this.creationDate = creationDate;
		this.lastUpdatedBy = lastUpdatedBy;
		this.lastUpdateDate = lastUpdateDate;
	}

	@Id
	@Column(name = "REPORT_ARGS_ID", unique = true, nullable = false)
	public int getReportArgsId() {
		return this.reportArgsId;
	}

	public void setReportArgsId(int reportArgsId) {
		this.reportArgsId = reportArgsId;
	}

	@Column(name = "REPORT_ID")
	public Integer getReportId() {
		return this.reportId;
	}

	public void setReportId(Integer reportId) {
		this.reportId = reportId;
	}

	@Column(name = "DISPLAY_SEQ")
	public Integer getDisplaySeq() {
		return this.displaySeq;
	}

	public void setDisplaySeq(Integer displaySeq) {
		this.displaySeq = displaySeq;
	}

	@Column(name = "SCREEN_DISPLAY_NAME", length = 50)
	public String getScreenDisplayName() {
		return this.screenDisplayName;
	}

	public void setScreenDisplayName(String screenDisplayName) {
		this.screenDisplayName = screenDisplayName;
	}

	@Column(name = "PARAMETER_NAME", length = 50)
	public String getParameterName() {
		return this.parameterName;
	}

	public void setParameterName(String parameterName) {
		this.parameterName = parameterName;
	}

	@Column(name = "LIST_ID")
	public Integer getListId() {
		return this.listId;
	}

	public void setListId(Integer listId) {
		this.listId = listId;
	}

	@Column(name = "PARAM_REQUIRED", length = 1)
	public String getParamRequired() {
		return this.paramRequired;
	}

	public void setParamRequired(String paramRequired) {
		this.paramRequired = paramRequired;
	}

	@Column(name = "MULTI_SELECT", length = 1)
	public String getMultiSelect() {
		return this.multiSelect;
	}

	public void setMultiSelect(String multiSelect) {
		this.multiSelect = multiSelect;
	}

	@Column(name = "CREATED_BY")
	public Integer getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(Integer createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "CREATION_DATE", length = 0)
	public Date getCreationDate() {
		return this.creationDate;
	}

	public void setCreationDate(Date creationDate) {
		this.creationDate = creationDate;
	}

	@Column(name = "LAST_UPDATED_BY")
	public Integer getLastUpdatedBy() {
		return this.lastUpdatedBy;
	}

	public void setLastUpdatedBy(Integer lastUpdatedBy) {
		this.lastUpdatedBy = lastUpdatedBy;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "LAST_UPDATE_DATE", length = 0)
	public Date getLastUpdateDate() {
		return this.lastUpdateDate;
	}

	public void setLastUpdateDate(Date lastUpdateDate) {
		this.lastUpdateDate = lastUpdateDate;
	}

}
