package com.osi.urm.domain;

// Generated Mar 3, 2017 8:07:44 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * OsiReports generated by hbm2java
 */
@Entity
@Table(name = "osi_reports")
public class OsiReports implements java.io.Serializable {

	private Integer reportId;
	private String reportName;
	private String userReportName;
	private String srcFileName;
	private Integer createdBy;
	private Date creationDate;
	private Integer lastUpdatedBy;
	private Date lastUpdateDate;
	private String reportType;
	private String outputType;
	private Integer businessGroupId;
	private Set<OsiRptGrpRpts> osiRptGrpRpts = new HashSet<OsiRptGrpRpts>(0);
	public OsiReports() {
	}

	public OsiReports(Integer reportId) {
		this.reportId = reportId;
	}

	public OsiReports(Integer reportId, String reportName, String userReportName,
			String srcFileName, Integer createdBy, Date creationDate,
			Integer lastUpdatedBy, Date lastUpdateDate, String reportType,
			String outputType) {
		this.reportId = reportId;
		this.reportName = reportName;
		this.userReportName = userReportName;
		this.srcFileName = srcFileName;
		this.createdBy = createdBy;
		this.creationDate = creationDate;
		this.lastUpdatedBy = lastUpdatedBy;
		this.lastUpdateDate = lastUpdateDate;
		this.reportType = reportType;
		this.outputType = outputType;
	}

	@Id
	@Column(name = "REPORT_ID", unique = true, nullable = false)
	public Integer getReportId() {
		return this.reportId;
	}

	public void setReportId(Integer reportId) {
		this.reportId = reportId;
	}

	@Column(name = "REPORT_NAME", length = 40)
	public String getReportName() {
		return this.reportName;
	}

	public void setReportName(String reportName) {
		this.reportName = reportName;
	}

	@Column(name = "USER_REPORT_NAME", length = 500)
	public String getUserReportName() {
		return this.userReportName;
	}

	public void setUserReportName(String userReportName) {
		this.userReportName = userReportName;
	}

	@Column(name = "SRC_FILE_NAME", length = 500)
	public String getSrcFileName() {
		return this.srcFileName;
	}

	public void setSrcFileName(String srcFileName) {
		this.srcFileName = srcFileName;
	}

	@Column(name = "CREATED_BY")
	public Integer getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(Integer createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "CREATION_DATE", length = 0)
	public Date getCreationDate() {
		return this.creationDate;
	}

	public void setCreationDate(Date creationDate) {
		this.creationDate = creationDate;
	}

	@Column(name = "LAST_UPDATED_BY")
	public Integer getLastUpdatedBy() {
		return this.lastUpdatedBy;
	}

	public void setLastUpdatedBy(Integer lastUpdatedBy) {
		this.lastUpdatedBy = lastUpdatedBy;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "LAST_UPDATE_DATE", length = 0)
	public Date getLastUpdateDate() {
		return this.lastUpdateDate;
	}

	public void setLastUpdateDate(Date lastUpdateDate) {
		this.lastUpdateDate = lastUpdateDate;
	}

	@Column(name = "REPORT_TYPE", length = 50)
	public String getReportType() {
		return this.reportType;
	}

	public void setReportType(String reportType) {
		this.reportType = reportType;
	}

	@Column(name = "OUTPUT_TYPE", length = 20)
	public String getOutputType() {
		return this.outputType;
	}

	public void setOutputType(String outputType) {
		this.outputType = outputType;
	}
	@Column(name = "BUSINESS_GROUP_ID")
	public Integer getBusinessGroupId() {
		return businessGroupId;
	}

	public void setBusinessGroupId(Integer businessGroupId) {
		this.businessGroupId = businessGroupId;
	}

	@OneToMany(mappedBy = "osiReports", fetch = FetchType.EAGER, cascade=CascadeType.ALL)
	public Set<OsiRptGrpRpts> getOsiRptGrpRpts() {
		return osiRptGrpRpts;
	}

	public void setOsiRptGrpRpts(Set<OsiRptGrpRpts> osiRptGrpRpts) {
		this.osiRptGrpRpts = osiRptGrpRpts;
	}
	
}
