package com.osi.urm.domain;

// Generated Jan 6, 2017 8:49:50 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * OsiSegmentStructureHdr generated by hbm2java
 */
@Entity
@Table(name = "osi_segment_structure_hdr")
public class OsiSegmentStructureHdr implements java.io.Serializable {

	private Integer segmentStructureHdrId;
	private String segmentStructureHdrDesc;
	//private Integer businessGroupId;
	private Integer active;
	private Integer createdBy;
	private Date createdDate;
	private Integer updatedBy;
	private Date updatedDate;
	private Set<OsiSegmentStructureDetails> osiSegmentStructureDetailses = new HashSet<OsiSegmentStructureDetails>(
			0);
	//private Set<OsiCoa> osiCoas = new HashSet<OsiCoa>(0);

	public OsiSegmentStructureHdr() {
	}

	public OsiSegmentStructureHdr(Integer segmentStructureHdrId/*,Integer businessGroupId*/,
			 String segmentStructureHdrDesc,
			Integer active) {
		this.segmentStructureHdrId = segmentStructureHdrId;
		this.segmentStructureHdrDesc = segmentStructureHdrDesc;
		this.active = active;
		//this.businessGroupId = businessGroupId;
	}

	public OsiSegmentStructureHdr(Integer segmentStructureHdrId,
			 String segmentStructureHdrDesc,/*Integer businessGroupId,*/
			Integer active, Integer createdBy, Date createdDate, Integer updatedBy,
			Date updatedDate,	Set<OsiSegmentStructureDetails> osiSegmentStructureDetailses) {//Set<OsiCoa> osiCoas
    	this.segmentStructureHdrId = segmentStructureHdrId;
		this.segmentStructureHdrDesc = segmentStructureHdrDesc;
		this.active = active;
		this.createdBy = createdBy;
		this.createdDate = createdDate;
		this.updatedBy = updatedBy;
		this.updatedDate = updatedDate;
		this.osiSegmentStructureDetailses = osiSegmentStructureDetailses;
		//this.osiCoas = osiCoas;
		//this.businessGroupId = businessGroupId;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	@Column(name = "SEGMENT_STRUCTURE_HDR_ID", unique = true, nullable = false)
	public Integer getSegmentStructureHdrId() {
		return this.segmentStructureHdrId;
	}

	public void setSegmentStructureHdrId(Integer segmentStructureHdrId) {
		this.segmentStructureHdrId = segmentStructureHdrId;
	}

	@Column(name = "SEGMENT_STRUCTURE_HDR", nullable = false)
	public String getSegmentStructureHdrDesc() {
		return this.segmentStructureHdrDesc;
	}

	public void setSegmentStructureHdrDesc(String segmentStructureHdrDesc) {
		this.segmentStructureHdrDesc = segmentStructureHdrDesc;
	}

	@Column(name = "ACTIVE", nullable = false)
	public Integer getActive() {
		return this.active;
	}

	public void setActive(Integer active) {
		this.active = active;
	}

	@Column(name = "CREATED_BY")
	public Integer getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(Integer createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATED_DATE", length = 0)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Column(name = "last_updated_by")
	public Integer getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(Integer updatedBy) {
		this.updatedBy = updatedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "last_update_date", length = 0)
	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "osiSegmentStructureHdr",cascade=CascadeType.ALL)
	public Set<OsiSegmentStructureDetails> getOsiSegmentStructureDetailses() {
		return this.osiSegmentStructureDetailses;
	}

	public void setOsiSegmentStructureDetailses(
			Set<OsiSegmentStructureDetails> osiSegmentStructureDetailses) {
		this.osiSegmentStructureDetailses = osiSegmentStructureDetailses;
	}

	/*@OneToMany(fetch = FetchType.LAZY, mappedBy = "osiSegmentStructureHdr")
	public Set<OsiCoa> getOsiCoas() {
		return this.osiCoas;
	}

	public void setOsiCoas(Set<OsiCoa> osiCoas) {
		this.osiCoas = osiCoas;
	}*/
	/*@Column(name = "org_id", nullable = false)
	public Integer getBusinessGroupId() {
		return businessGroupId;
	}

	public void setBusinessGroupId(Integer businessGroupId) {
		this.businessGroupId = businessGroupId;
	}*/
	
}
