package com.osi.urm.domain;

import java.util.HashSet;
import java.util.Set;

// Generated Jan 6, 2017 8:49:50 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Transient;

/**
 * OsiSegmentStructureDetails generated by hbm2java
 */
@Entity
@Table(name = "osi_segment_structure_details")
public class OsiSegmentStructureDetails implements java.io.Serializable {

	private Integer segmentStructureDetailsId;
	private OsiSegmentStructureHdr osiSegmentStructureHdr;
	//private Integer businessGroupId;
	private String segmentStructureDetailsDesc;
	private Integer segmentStructureDetailsSeq;
	//private Integer depSegmentStructureDetailsId;
	private Integer isSqlReqdForValidation;
	private String lovDataForValidation;
	private String sqlQueryForValidation;
	private Integer osiSegmentStructureHdrId;
	private Set<OsiLookupValues> osiLookupValuesList = new HashSet<OsiLookupValues>();
	private Integer createdBy;
	private Integer updatedBy;
	public OsiSegmentStructureDetails() {
	}

	public OsiSegmentStructureDetails(Integer segmentStructureDetailsId,
			OsiSegmentStructureHdr osiSegmentStructureHdr,
			/*Integer businessGroupId,*/
			String segmentStructureDetailsDesc, Integer segmentStructureDetailsSeq) {
			//Integer depSegmentStructureDetailsId) {
		this.segmentStructureDetailsId = segmentStructureDetailsId;
		this.osiSegmentStructureHdr = osiSegmentStructureHdr;
	//	this.businessGroupId = businessGroupId;
		this.segmentStructureDetailsDesc = segmentStructureDetailsDesc;
		this.segmentStructureDetailsSeq = segmentStructureDetailsSeq;
	//	this.depSegmentStructureDetailsId = depSegmentStructureDetailsId;
	}

	public OsiSegmentStructureDetails(Integer segmentStructureDetailsId,
			OsiSegmentStructureHdr osiSegmentStructureHdr,
		/*	Integer businessGroupId,*/
			String segmentStructureDetailsDesc, Integer segmentStructureDetailsSeq,
			/*Integer depSegmentStructureDetailsId,*/ Integer isSqlReqdForValidation,
			String lovDataForValidation, String sqlQueryForValidation) {
		this.segmentStructureDetailsId = segmentStructureDetailsId;
		this.osiSegmentStructureHdr = osiSegmentStructureHdr;
	//	this.businessGroupId = businessGroupId;
		this.segmentStructureDetailsDesc = segmentStructureDetailsDesc;
		this.segmentStructureDetailsSeq = segmentStructureDetailsSeq;
		//this.depSegmentStructureDetailsId = depSegmentStructureDetailsId;
		this.isSqlReqdForValidation = isSqlReqdForValidation;
		this.lovDataForValidation = lovDataForValidation;
		this.sqlQueryForValidation = sqlQueryForValidation;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.AUTO)
	@Column(name = "SEGMENT_STRUCTURE_DETAILS_ID", unique = true, nullable = false)
	public Integer getSegmentStructureDetailsId() {
		return this.segmentStructureDetailsId;
	}

	public void setSegmentStructureDetailsId(Integer segmentStructureDetailsId) {
		this.segmentStructureDetailsId = segmentStructureDetailsId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SEGMENT_STRUCTURE_HDR_ID", nullable = false)
	public OsiSegmentStructureHdr getOsiSegmentStructureHdr() {
		return this.osiSegmentStructureHdr;
	}

	public void setOsiSegmentStructureHdr(
			OsiSegmentStructureHdr osiSegmentStructureHdr) {
		this.osiSegmentStructureHdr = osiSegmentStructureHdr;
	}
	
	/*@Column(name = "org_id", nullable = false)
	public Integer getBusinessGroupId() {
		return businessGroupId;
	}

	public void setBusinessGroupId(Integer businessGroupId) {
		this.businessGroupId = businessGroupId;
	}*/

	@Column(name = "SEGMENT_NAME", nullable = false)
	public String getSegmentStructureDetailsDesc() {
		return this.segmentStructureDetailsDesc;
	}

	public void setSegmentStructureDetailsDesc(
			String segmentStructureDetailsDesc) {
		this.segmentStructureDetailsDesc = segmentStructureDetailsDesc;
	}

	@Column(name = "SEGMENT_SEQ", nullable = false)
	public Integer getSegmentStructureDetailsSeq() {
		return this.segmentStructureDetailsSeq;
	}

	public void setSegmentStructureDetailsSeq(Integer segmentStructureDetailsSeq) {
		this.segmentStructureDetailsSeq = segmentStructureDetailsSeq;
	}

	/*@Column(name = "DEP_SEGMENT_STRUCTURE_DETAILS_ID", nullable = false)
	public Integer getDepSegmentStructureDetailsId() {
		return this.depSegmentStructureDetailsId;
	}

	public void setDepSegmentStructureDetailsId(Integer depSegmentStructureDetailsId) {
		this.depSegmentStructureDetailsId = depSegmentStructureDetailsId;
	}
*/
	@Column(name = "IS_SQL_REQD_FOR_VALIDATION")
	public Integer getIsSqlReqdForValidation() {
		return this.isSqlReqdForValidation;
	}

	public void setIsSqlReqdForValidation(Integer isSqlReqdForValidation) {
		this.isSqlReqdForValidation = isSqlReqdForValidation;
	}

	@Column(name = "LOV_DATA_FOR_VALIDATION")
	public String getLovDataForValidation() {
		return this.lovDataForValidation;
	}

	public void setLovDataForValidation(String lovDataForValidation) {
		this.lovDataForValidation = lovDataForValidation;
	}

	@Column(name = "SQL_QUERY_FOR_VALIDATION")
	public String getSqlQueryForValidation() {
		return this.sqlQueryForValidation;
	}

	public void setSqlQueryForValidation(String sqlQueryForValidation) {
		this.sqlQueryForValidation = sqlQueryForValidation;
	}
	 @Transient
	public Set<OsiLookupValues> getOsiLookupValuesList() {
		return osiLookupValuesList;
	}

	public void setOsiLookupValuesList(Set<OsiLookupValues> osiLookupValuesList) {
		this.osiLookupValuesList = osiLookupValuesList;
	}
	
	@Transient
	public Integer getOsiSegmentStructureHdrId() {
		return osiSegmentStructureHdrId;
	}

	public void setOsiSegmentStructureHdrId(Integer osiSegmentStructureHdrId) {
		this.osiSegmentStructureHdrId = osiSegmentStructureHdrId;
	}

	@Column(name = "CREATED_BY")
	public Integer getCreatedBy() {
		return createdBy;
	}

	public void setCreatedBy(Integer createdBy) {
		this.createdBy = createdBy;
	}

	@Column(name = "last_updated_by")
	public Integer getUpdatedBy() {
		return updatedBy;
	}

	public void setUpdatedBy(Integer updatedBy) {
		this.updatedBy = updatedBy;
	}
}
