package com.osi.urm.domain;

// Generated Dec 1, 2016 5:20:37 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * OsiUserOperationExcl generated by hbm2java
 */
@Entity
@Table(name = "osi_user_operation_excl")
public class OsiUserOperationExcl implements java.io.Serializable {

	private Integer id;
	private OsiFunctions osiFunctions;
	private OsiOperations osiOperations;
	
	private Integer employeeId;
	private Integer createdBy;
	private Date createdDate;
	private Integer updatedBy;
	private Date updatedDate;
	private Integer businessGroupId;

	public OsiUserOperationExcl() {
	}

	public OsiUserOperationExcl(Integer id, OsiFunctions osiFunctions,
			OsiOperations osiOperations, Integer employeeId) {
		this.id = id;
		this.osiFunctions = osiFunctions;
		this.osiOperations = osiOperations;
		this.employeeId = employeeId;
	}

	public OsiUserOperationExcl(Integer id, OsiFunctions osiFunctions,
			OsiOperations osiOperations, Integer employeeId, Integer createdBy,
			Date createdDate, Integer updatedBy, Date updatedDate) {
		this.id = id;
		this.osiFunctions = osiFunctions;
		this.osiOperations = osiOperations;
		this.employeeId=employeeId;
		this.createdBy = createdBy;
		this.createdDate = createdDate;
		this.updatedBy = updatedBy;
		this.updatedDate = updatedDate;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	@GeneratedValue(strategy=GenerationType.AUTO)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "func_id", nullable = false)
	public OsiFunctions getOsiFunctions() {
		return this.osiFunctions;
	}

	public void setOsiFunctions(OsiFunctions osiFunctions) {
		this.osiFunctions = osiFunctions;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "op_id", nullable = false)
	public OsiOperations getOsiOperations() {
		return this.osiOperations;
	}

	public void setOsiOperations(OsiOperations osiOperations) {
		this.osiOperations = osiOperations;
	}


	@Column(name = "created_by")
	public Integer getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(Integer createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_date", length = 0)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Column(name = "updated_by")
	public Integer getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(Integer updatedBy) {
		this.updatedBy = updatedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_date", length = 0)
	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}
	
	@Column(name = "business_group_id")
	public Integer getBusinessGroupId() {
		return businessGroupId;
	}

	public void setBusinessGroupId(Integer businessGroupId) {
		this.businessGroupId = businessGroupId;
	}
	
	@Column(name = "user_id")
	public Integer getEmployeeId() {
		return employeeId;
	}

	public void setEmployeeId(Integer employeeId) {
		this.employeeId = employeeId;
	}

}
