package com.osi.urm.domain;

// Generated Jan 6, 2017 8:49:50 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * OsiCoa generated by hbm2java
 */
@Entity
@Table(name = "osi_key_flex")
public class OsiKeyFlex implements java.io.Serializable {
	private Integer keyFlexId;
	private Integer businessGroupId;
	private String name;
	private String value;
	public OsiKeyFlex() {
	}

	@Id
	@SequenceGenerator(name = "seq_osi_key_flex", sequenceName = "seq_osi_key_flex",allocationSize=1)
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "seq_osi_key_flex")
	@Column(name = "KEY_FLEX_ID", unique = true, nullable = false)
	public Integer getKeyFlexId() {
		return keyFlexId;
	}



	public void setKeyFlexId(Integer keyFlexId) {
		this.keyFlexId = keyFlexId;
	}



	@Column(name = "ORG_ID", unique = true, nullable = false)
	public Integer getBusinessGroupId() {
		return businessGroupId;
	}
	public void setBusinessGroupId(Integer businessGroupId) {
		this.businessGroupId = businessGroupId;
	}
	@Column(name = "NAME", unique = true, nullable = false)
	public String getName() {
		return name;
	}
	public void setName(String name) {
		this.name = name;
	}
	@Column(name = "VALUE", unique = true, nullable = false)
	public String getValue() {
		return value;
	}
	public void setValue(String value) {
		this.value = value;
	}

}
