package com.osi.urm.domain;

// Generated Mar 3, 2017 8:07:44 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * OsiLists generated by hbm2java
 */
@Entity
@Table(name = "osi_lists")
public class OsiLists implements java.io.Serializable {

	private int listId;
	private String listName;
	private String listDescription;
	private String validationType;
	private String listDataType;
	private Integer listDataMaxSize;
	private Integer createdBy;
	private Date creationDate;
	private Integer lastUpdatedBy;
	private Date lastUpdateDate;
	private String dateFormat;

	public OsiLists() {
	}

	public OsiLists(int listId) {
		this.listId = listId;
	}

	public OsiLists(int listId, String listName, String listDescription,
			String validationType, String listDataType,
			Integer listDataMaxSize, Integer createdBy, Date creationDate,
			Integer lastUpdatedBy, Date lastUpdateDate, String dateFormat) {
		this.listId = listId;
		this.listName = listName;
		this.listDescription = listDescription;
		this.validationType = validationType;
		this.listDataType = listDataType;
		this.listDataMaxSize = listDataMaxSize;
		this.createdBy = createdBy;
		this.creationDate = creationDate;
		this.lastUpdatedBy = lastUpdatedBy;
		this.lastUpdateDate = lastUpdateDate;
		this.dateFormat = dateFormat;
	}

	@Id
	@Column(name = "LIST_ID", unique = true, nullable = false)
	public int getListId() {
		return this.listId;
	}

	public void setListId(int listId) {
		this.listId = listId;
	}

	@Column(name = "LIST_NAME", length = 100)
	public String getListName() {
		return this.listName;
	}

	public void setListName(String listName) {
		this.listName = listName;
	}

	@Column(name = "LIST_DESCRIPTION")
	public String getListDescription() {
		return this.listDescription;
	}

	public void setListDescription(String listDescription) {
		this.listDescription = listDescription;
	}

	@Column(name = "VALIDATION_TYPE", length = 1)
	public String getValidationType() {
		return this.validationType;
	}

	public void setValidationType(String validationType) {
		this.validationType = validationType;
	}

	@Column(name = "LIST_DATA_TYPE", length = 1)
	public String getListDataType() {
		return this.listDataType;
	}

	public void setListDataType(String listDataType) {
		this.listDataType = listDataType;
	}

	@Column(name = "LIST_DATA_MAX_SIZE")
	public Integer getListDataMaxSize() {
		return this.listDataMaxSize;
	}

	public void setListDataMaxSize(Integer listDataMaxSize) {
		this.listDataMaxSize = listDataMaxSize;
	}

	@Column(name = "CREATED_BY")
	public Integer getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(Integer createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "CREATION_DATE", length = 0)
	public Date getCreationDate() {
		return this.creationDate;
	}

	public void setCreationDate(Date creationDate) {
		this.creationDate = creationDate;
	}

	@Column(name = "LAST_UPDATED_BY")
	public Integer getLastUpdatedBy() {
		return this.lastUpdatedBy;
	}

	public void setLastUpdatedBy(Integer lastUpdatedBy) {
		this.lastUpdatedBy = lastUpdatedBy;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "LAST_UPDATE_DATE", length = 0)
	public Date getLastUpdateDate() {
		return this.lastUpdateDate;
	}

	public void setLastUpdateDate(Date lastUpdateDate) {
		this.lastUpdateDate = lastUpdateDate;
	}

	@Column(name = "DATE_FORMAT", length = 20)
	public String getDateFormat() {
		return this.dateFormat;
	}

	public void setDateFormat(String dateFormat) {
		this.dateFormat = dateFormat;
	}

}
