package com.osi.urm.domain;

// Generated Mar 3, 2017 8:07:44 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * OsiListSql generated by hbm2java
 */
@Entity
@Table(name = "osi_list_sql")
public class OsiListSql implements java.io.Serializable {

	private int listSqlId;
	private Integer listId;
	private String listSql;
	private Integer createdBy;
	private Date creationDate;
	private Integer lastUpdatedBy;
	private Date lastUpdateDate;

	public OsiListSql() {
	}

	public OsiListSql(int listSqlId) {
		this.listSqlId = listSqlId;
	}

	public OsiListSql(int listSqlId, Integer listId, String listSql,
			Integer createdBy, Date creationDate, Integer lastUpdatedBy,
			Date lastUpdateDate) {
		this.listSqlId = listSqlId;
		this.listId = listId;
		this.listSql = listSql;
		this.createdBy = createdBy;
		this.creationDate = creationDate;
		this.lastUpdatedBy = lastUpdatedBy;
		this.lastUpdateDate = lastUpdateDate;
	}

	@Id
	@Column(name = "LIST_SQL_ID", unique = true, nullable = false)
	public int getListSqlId() {
		return this.listSqlId;
	}

	public void setListSqlId(int listSqlId) {
		this.listSqlId = listSqlId;
	}

	@Column(name = "LIST_ID")
	public Integer getListId() {
		return this.listId;
	}

	public void setListId(Integer listId) {
		this.listId = listId;
	}

	@Column(name = "LIST_SQL")
	public String getListSql() {
		return this.listSql;
	}

	public void setListSql(String listSql) {
		this.listSql = listSql;
	}

	@Column(name = "CREATED_BY")
	public Integer getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(Integer createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "CREATION_DATE", length = 0)
	public Date getCreationDate() {
		return this.creationDate;
	}

	public void setCreationDate(Date creationDate) {
		this.creationDate = creationDate;
	}

	@Column(name = "LAST_UPDATED_BY")
	public Integer getLastUpdatedBy() {
		return this.lastUpdatedBy;
	}

	public void setLastUpdatedBy(Integer lastUpdatedBy) {
		this.lastUpdatedBy = lastUpdatedBy;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "LAST_UPDATE_DATE", length = 0)
	public Date getLastUpdateDate() {
		return this.lastUpdateDate;
	}

	public void setLastUpdateDate(Date lastUpdateDate) {
		this.lastUpdateDate = lastUpdateDate;
	}

}
