package com.osi.urm.domain;

// Generated Mar 3, 2017 8:07:44 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * OsiRptGroups generated by hbm2java
 */
@Entity
@Table(name = "osi_rpt_groups")
public class OsiRptGroups implements java.io.Serializable {

	private Integer rptGrpId;
	private Integer active;
	private String rptGrpName;
	private Integer createdBy;
	private Date creationDate;
	private Integer lastUpdatedBy;
	private Date lastUpdateDate;
	private Integer businessGroupId;

	private Set<OsiRptGrpRpts> osiRptGrpRpts = new HashSet<OsiRptGrpRpts>(0);
	
	public OsiRptGroups() {
	}

	public OsiRptGroups(Integer rptGrpId) {
		this.rptGrpId = rptGrpId;
	}

	public OsiRptGroups(Integer rptGrpId, Integer active, String rptGrpName,
			Integer createdBy, Date creationDate, Integer lastUpdatedBy,
			Date lastUpdateDate) {
		this.rptGrpId = rptGrpId;
		this.active = active;
		this.rptGrpName = rptGrpName;
		this.createdBy = createdBy;
		this.creationDate = creationDate;
		this.lastUpdatedBy = lastUpdatedBy;
		this.lastUpdateDate = lastUpdateDate;
	}

	@Id
	@Column(name = "RPT_GRP_ID", unique = true, nullable = false)
	@SequenceGenerator(name="seq_osi_rpt_groups", sequenceName="seq_osi_rpt_groups",allocationSize=1)
	@GeneratedValue(strategy=GenerationType.SEQUENCE, generator="seq_osi_rpt_groups")
	public Integer getRptGrpId() {
		return this.rptGrpId;
	}

	public void setRptGrpId(Integer rptGrpId) {
		this.rptGrpId = rptGrpId;
	}

	@Column(name = "ACTIVE")
	public Integer getActive() {
		return this.active;
	}

	public void setActive(Integer active) {
		this.active = active;
	}

	@Column(name = "RPT_GRP_NAME")
	public String getRptGrpName() {
		return this.rptGrpName;
	}

	public void setRptGrpName(String rptGrpName) {
		this.rptGrpName = rptGrpName;
	}

	@Column(name = "CREATED_BY")
	public Integer getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(Integer createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "CREATION_DATE", length = 0)
	public Date getCreationDate() {
		return this.creationDate;
	}

	public void setCreationDate(Date creationDate) {
		this.creationDate = creationDate;
	}

	@Column(name = "LAST_UPDATED_BY")
	public Integer getLastUpdatedBy() {
		return this.lastUpdatedBy;
	}

	public void setLastUpdatedBy(Integer lastUpdatedBy) {
		this.lastUpdatedBy = lastUpdatedBy;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "LAST_UPDATE_DATE", length = 0)
	public Date getLastUpdateDate() {
		return this.lastUpdateDate;
	}

	public void setLastUpdateDate(Date lastUpdateDate) {
		this.lastUpdateDate = lastUpdateDate;
	}
	@OneToMany(mappedBy = "osiRptGroups", fetch = FetchType.EAGER, cascade=CascadeType.ALL)
	public Set<OsiRptGrpRpts> getOsiRptGrpRpts() {
		return osiRptGrpRpts;
	}

	public void setOsiRptGrpRpts(Set<OsiRptGrpRpts> osiRptGrpRpts) {
		this.osiRptGrpRpts = osiRptGrpRpts;
	}
	
	@JoinColumn(name = "BUSINESS_GROUP_ID", nullable = false)
	public Integer getBusinessGroupId() {
		return businessGroupId;
	}

	public void setBusinessGroupId(Integer businessGroupId) {
		this.businessGroupId = businessGroupId;
	}
}
