package com.osi.ems.service.dto;
// Generated Oct 10, 2017 12:00:12 PM by Hibernate Tools 5.2.3.Final

import java.util.Date;

/**
 * OsiCurrencies generated by hbm2java
 */
public class OsiCurrenciesDTO implements java.io.Serializable {

	private Integer currencyId;
	private String currencyName;
	private String currencyCode;
	private Integer active;
	private Integer createdBy;
	private Date createdDate;
	private Integer updatedBy;
	private Date lastUpdateDate;

	public OsiCurrenciesDTO() {
	}

	public OsiCurrenciesDTO(String currencyName, String currencyCode, Integer active, Integer createdBy, Date createdDate,
			Integer updatedBy, Date lastUpdateDate) {
		this.currencyName = currencyName;
		this.currencyCode = currencyCode;
		this.active = active;
		this.createdBy = createdBy;
		this.createdDate = createdDate;
		this.updatedBy = updatedBy;
		this.lastUpdateDate = lastUpdateDate;
	}

	public Integer getCurrencyId() {
		return this.currencyId;
	}

	public void setCurrencyId(Integer currencyId) {
		this.currencyId = currencyId;
	}

	public String getCurrencyName() {
		return this.currencyName;
	}

	public void setCurrencyName(String currencyName) {
		this.currencyName = currencyName;
	}

	public String getCurrencyCode() {
		return this.currencyCode;
	}

	public void setCurrencyCode(String currencyCode) {
		this.currencyCode = currencyCode;
	}

	public Integer getActive() {
		return this.active;
	}

	public void setActive(Integer active) {
		this.active = active;
	}

	public Integer getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(Integer createdBy) {
		this.createdBy = createdBy;
	}

	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	public Integer getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(Integer updatedBy) {
		this.updatedBy = updatedBy;
	}

	public Date getLastUpdateDate() {
		return this.lastUpdateDate;
	}

	public void setLastUpdateDate(Date lastUpdateDate) {
		this.lastUpdateDate = lastUpdateDate;
	}

}
