package com.osi.ems.mapper;


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
* OsiFunctions generated by hbm2java
*/
@Entity
@Table(name = "osi_organizations")
public class OsiOrganizations implements java.io.Serializable{
	/**
	 * 
	 */
	private static final long serialVersionUID = 427856318977822644L;
	private Integer orgId;
	private String orgName;
	public OsiOrganizations() {
	}
	public OsiOrganizations(Integer orgId, String orgName) {
			this.orgId = orgId;
			this.orgName = orgName;
			
			
		}
	@Id
	@Column(name = "org_id", unique = true, nullable = false)
	@GeneratedValue(strategy=GenerationType.AUTO)
	public Integer getOrgId() {
		return orgId;
	}
	public void setOrgId(Integer orgId) {
		this.orgId = orgId;
	}


	@Column(name = "org_name", nullable = false, length = 100)
	
	public String getOrgName() {
		return orgName;
	}
	public void setOrgName(String orgName) {
		this.orgName = orgName;
	}
}
