package com.osi.urm.service.dto;

// Generated Mar 3, 2017 8:07:44 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * OsiListValues generated by hbm2java
 */
public class OsiListValuesDTO implements java.io.Serializable {

	private int listValuesId;
	private Integer listId;
	private String listValue;
	private Integer listSeq;
	private Integer createdBy;
	private Date creationDate;
	private Integer lastUpdatedBy;
	private Date lastUpdateDate;

	public OsiListValuesDTO() {
	}

	public OsiListValuesDTO(int listValuesId) {
		this.listValuesId = listValuesId;
	}

	public OsiListValuesDTO(int listValuesId, Integer listId, String listValue,
			Integer listSeq, Integer createdBy, Date creationDate,
			Integer lastUpdatedBy, Date lastUpdateDate) {
		this.listValuesId = listValuesId;
		this.listId = listId;
		this.listValue = listValue;
		this.listSeq = listSeq;
		this.createdBy = createdBy;
		this.creationDate = creationDate;
		this.lastUpdatedBy = lastUpdatedBy;
		this.lastUpdateDate = lastUpdateDate;
	}

	public int getListValuesId() {
		return this.listValuesId;
	}

	public void setListValuesId(int listValuesId) {
		this.listValuesId = listValuesId;
	}

	public Integer getListId() {
		return this.listId;
	}

	public void setListId(Integer listId) {
		this.listId = listId;
	}

	public String getListValue() {
		return this.listValue;
	}

	public void setListValue(String listValue) {
		this.listValue = listValue;
	}

	public Integer getListSeq() {
		return this.listSeq;
	}

	public void setListSeq(Integer listSeq) {
		this.listSeq = listSeq;
	}

	public Integer getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(Integer createdBy) {
		this.createdBy = createdBy;
	}

	public Date getCreationDate() {
		return this.creationDate;
	}

	public void setCreationDate(Date creationDate) {
		this.creationDate = creationDate;
	}

	public Integer getLastUpdatedBy() {
		return this.lastUpdatedBy;
	}

	public void setLastUpdatedBy(Integer lastUpdatedBy) {
		this.lastUpdatedBy = lastUpdatedBy;
	}

	public Date getLastUpdateDate() {
		return this.lastUpdateDate;
	}

	public void setLastUpdateDate(Date lastUpdateDate) {
		this.lastUpdateDate = lastUpdateDate;
	}
}
