package com.osi.urm.service.dto;

// Generated Mar 3, 2017 8:07:44 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * OsiListSql generated by hbm2java
 */
public class OsiListSqlDTO implements java.io.Serializable {

	private int listSqlId;
	private Integer listId;
	private String listSql;
	private Integer createdBy;
	private Date creationDate;
	private Integer lastUpdatedBy;
	private Date lastUpdateDate;

	public OsiListSqlDTO() {
	}

	public OsiListSqlDTO(int listSqlId) {
		this.listSqlId = listSqlId;
	}

	public OsiListSqlDTO(int listSqlId, Integer listId, String listSql,
			Integer createdBy, Date creationDate, Integer lastUpdatedBy,
			Date lastUpdateDate) {
		this.listSqlId = listSqlId;
		this.listId = listId;
		this.listSql = listSql;
		this.createdBy = createdBy;
		this.creationDate = creationDate;
		this.lastUpdatedBy = lastUpdatedBy;
		this.lastUpdateDate = lastUpdateDate;
	}

	public int getListSqlId() {
		return this.listSqlId;
	}

	public void setListSqlId(int listSqlId) {
		this.listSqlId = listSqlId;
	}

	public Integer getListId() {
		return this.listId;
	}

	public void setListId(Integer listId) {
		this.listId = listId;
	}

	public String getListSql() {
		return this.listSql;
	}

	public void setListSql(String listSql) {
		this.listSql = listSql;
	}

	public Integer getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(Integer createdBy) {
		this.createdBy = createdBy;
	}

	public Date getCreationDate() {
		return this.creationDate;
	}

	public void setCreationDate(Date creationDate) {
		this.creationDate = creationDate;
	}

	public Integer getLastUpdatedBy() {
		return this.lastUpdatedBy;
	}

	public void setLastUpdatedBy(Integer lastUpdatedBy) {
		this.lastUpdatedBy = lastUpdatedBy;
	}

	public Date getLastUpdateDate() {
		return this.lastUpdateDate;
	}

	public void setLastUpdateDate(Date lastUpdateDate) {
		this.lastUpdateDate = lastUpdateDate;
	}
}
