package com.osi.urm.service.dto;

// Generated Mar 3, 2017 8:07:44 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * OsiRptGroups generated by hbm2java
 */
public class OsiRptGroupsDTO implements java.io.Serializable {

	private Integer rptGrpId;
	private Integer active;
	private String rptGrpName;
	private Integer createdBy;
	private Date creationDate;
	private Integer lastUpdatedBy;
	private Date lastUpdateDate;
	private Integer businessGroupId;
	private Set<OsiRptGrpRptsDTO> osiRptGrpRpts = new HashSet<OsiRptGrpRptsDTO>(0);
	public OsiRptGroupsDTO() {
	}

	public OsiRptGroupsDTO(Integer rptGrpId) {
		this.rptGrpId = rptGrpId;
	}

	public OsiRptGroupsDTO(Integer rptGrpId, Integer active, String rptGrpName,
			Integer createdBy, Date creationDate, Integer lastUpdatedBy,
			Date lastUpdateDate) {
		this.rptGrpId = rptGrpId;
		this.active = active;
		this.rptGrpName = rptGrpName;
		this.createdBy = createdBy;
		this.creationDate = creationDate;
		this.lastUpdatedBy = lastUpdatedBy;
		this.lastUpdateDate = lastUpdateDate;
	}

	public Integer getRptGrpId() {
		return this.rptGrpId;
	}

	public void setRptGrpId(Integer rptGrpId) {
		this.rptGrpId = rptGrpId;
	}

	public Integer getActive() {
		return this.active;
	}

	public void setActive(Integer active) {
		this.active = active;
	}

	public String getRptGrpName() {
		return this.rptGrpName;
	}

	public void setRptGrpName(String rptGrpName) {
		this.rptGrpName = rptGrpName;
	}

	public Integer getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(Integer createdBy) {
		this.createdBy = createdBy;
	}

	public Date getCreationDate() {
		return this.creationDate;
	}

	public void setCreationDate(Date creationDate) {
		this.creationDate = creationDate;
	}

	public Integer getLastUpdatedBy() {
		return this.lastUpdatedBy;
	}

	public void setLastUpdatedBy(Integer lastUpdatedBy) {
		this.lastUpdatedBy = lastUpdatedBy;
	}

	public Date getLastUpdateDate() {
		return this.lastUpdateDate;
	}

	public void setLastUpdateDate(Date lastUpdateDate) {
		this.lastUpdateDate = lastUpdateDate;
	}

	public Set<OsiRptGrpRptsDTO> getOsiRptGrpRpts() {
		return osiRptGrpRpts;
	}

	public void setOsiRptGrpRpts(Set<OsiRptGrpRptsDTO> osiRptGrpRpts) {
		this.osiRptGrpRpts = osiRptGrpRpts;
	}

	public Integer getBusinessGroupId() {
		return businessGroupId;
	}

	public void setBusinessGroupId(Integer businessGroupId) {
		this.businessGroupId = businessGroupId;
	}
}
