package com.osi.ems.service.dto;
// default package
// Generated Dec 5, 2017 4:13:32 PM by Hibernate Tools 5.2.3.Final

import java.util.Date;

import com.osi.ems.domain.OsiGrades;

/**
 * OsiTitleGradesId generated by hbm2java
 */
public class OsiTitleGradesDTO implements java.io.Serializable {

	private Integer titleGradeId;
	private Integer titleId;
	private OsiGrades gradeId;
	private Integer createdBy;
	private Date creationDate;
	private Integer lastUpdatedBy;
	private Date lastUpdateDate;

	public OsiTitleGradesDTO() {
	}

	public Integer getTitleGradeId() {
		return this.titleGradeId;
	}

	public void setTitleGradeId(Integer titleGradeId) {
		this.titleGradeId = titleGradeId;
	}

	public Integer getTitleId() {
		return this.titleId;
	}

	public void setTitleId(Integer titleId) {
		this.titleId = titleId;
	}

	public OsiGrades getGradeId() {
		return this.gradeId;
	}

	public void setGradeId(OsiGrades gradeId) {
		this.gradeId = gradeId;
	}

	public int getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(Integer createdBy) {
		this.createdBy = createdBy;
	}

	public Date getCreationDate() {
		return this.creationDate;
	}

	public void setCreationDate(Date creationDate) {
		this.creationDate = creationDate;
	}

	public int getLastUpdatedBy() {
		return this.lastUpdatedBy;
	}

	public void setLastUpdatedBy(Integer lastUpdatedBy) {
		this.lastUpdatedBy = lastUpdatedBy;
	}

	public Date getLastUpdateDate() {
		return this.lastUpdateDate;
	}

	public void setLastUpdateDate(Date lastUpdateDate) {
		this.lastUpdateDate = lastUpdateDate;
	}

}
