package com.osi.ems.domain;
// Generated Dec 8, 2017 2:18:30 PM by Hibernate Tools 5.2.3.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * OsiCertifications generated by hbm2java
 */
@Entity
@Table(name = "osi_certifications")
public class OsiCertifications implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -4915885041798877379L;
	private Integer certificationId;
	private String certificationName;
	private String certificationCode;
	private String certificationAddInfo;
	private Integer osiCertificationGroupId;
	private Set<OsiCertificationTags> osiCertificationTags;
	private String issuedBy;
	private Integer active;
	private Integer createdBy;
	private Date createdDate;
	private Integer updatedBy;
	private Date lastUpdateDate;

	private OsiCertificationGroups certificationGroup;

	public OsiCertifications() {
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "certification_id", unique = true, nullable = false)
	public Integer getCertificationId() {
		return this.certificationId;
	}

	public void setCertificationId(Integer certificationId) {
		this.certificationId = certificationId;
	}

	@Column(name = "certification_name", length = 100)
	public String getCertificationName() {
		return this.certificationName;
	}

	public void setCertificationName(String certificationName) {
		this.certificationName = certificationName;
	}

	@Column(name = "certification_code", length = 50)
	public String getCertificationCode() {
		return this.certificationCode;
	}

	public void setCertificationCode(String certificationCode) {
		this.certificationCode = certificationCode;
	}

	@Column(name = "certification_add_info", length = 100)
	public String getCertificationAddInfo() {
		return this.certificationAddInfo;
	}

	public void setCertificationAddInfo(String certificationAddInfo) {
		this.certificationAddInfo = certificationAddInfo;
	}

	@Column(name = "issued_by", length = 100)
	public String getIssuedBy() {
		return this.issuedBy;
	}

	public void setIssuedBy(String issuedBy) {
		this.issuedBy = issuedBy;
	}

	@Column(name = "active")
	public Integer getActive() {
		return this.active;
	}

	public void setActive(Integer active) {
		this.active = active;
	}

	@Column(name = "created_by", updatable = false)
	public Integer getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(Integer createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_date", length = 19, updatable = false)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Column(name = "updated_by")
	public Integer getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(Integer updatedBy) {
		this.updatedBy = updatedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "last_update_date", length = 19)
	public Date getLastUpdateDate() {
		return this.lastUpdateDate;
	}

	public void setLastUpdateDate(Date lastUpdateDate) {
		this.lastUpdateDate = lastUpdateDate;
	}

	public Integer getOsiCertificationGroupId() {
		return osiCertificationGroupId;
	}

	@OneToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "osi_certification_tag_mapping", joinColumns = @JoinColumn(name = "certification_id"), inverseJoinColumns = @JoinColumn(name = "tag_id"))
	public Set<OsiCertificationTags> getOsiCertificationTags() {
		return osiCertificationTags;
	}

	public void setOsiCertificationGroupId(Integer osiCertificationGroupId) {
		this.osiCertificationGroupId = osiCertificationGroupId;
	}

	public void setOsiCertificationTags(Set<OsiCertificationTags> osiCertificationTags) {
		this.osiCertificationTags = osiCertificationTags;
	}

	@OneToOne
	@JoinColumn(name = "osiCertificationGroupId", insertable = false, updatable = false)
	public OsiCertificationGroups getCertificationGroup() {
		return certificationGroup;
	}

	public void setCertificationGroup(OsiCertificationGroups certificationGroup) {
		this.certificationGroup = certificationGroup;
	}

}
