package com.osi.ems.domain;


//Generated Dec 1, 2016 5:20:37 PM by Hibernate Tools 3.4.0.CR1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;


/**
* OsiCategoryFields generated by hbm2java
*/
@Entity
@Table(name = "osi_category_fields")
public class OsiCategoryFields implements java.io.Serializable {

	
	/**
	 * 
	 */
	private static final long serialVersionUID = 6646092332501208307L;
	private Integer id;
	private String colName;
	private String colValue;
	private String colType;
	private String colSrcType;
	private String colSrc;
	private Integer nullable;
	private Integer seq;
	private String srcpValid;


	private OsiCategories osiCategory;

	public OsiCategoryFields() {
	}



	public OsiCategoryFields(Integer id,String colName,String colValue,String colType,String colSrcType,OsiCategories osiCategory,
			                 String colSrc,Integer nullable,Integer seq,String srcpValid) {
		this.id = id;
		this.colName = colName;
		this.colValue = colValue;
		this.colType = colType;
		this.osiCategory=osiCategory;
		this.colSrcType = colSrcType;
		this.colSrc = colSrc;
		this.nullable = nullable;
		this.seq = seq;
		this.srcpValid = srcpValid;
	}

	@Id
	@Column(name = "category_field_id", unique = true, nullable = false)
	@GeneratedValue(strategy=GenerationType.AUTO)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	
	@Column(name = "column_name", nullable = false)
	public String getColName() {
		return colName;
	}



	public void setColName(String colName) {
		this.colName = colName;
	}
	
	@Column(name = "column_value", nullable = false)
	public String getColValue() {
		return colValue;
	}



	public void setColValue(String colValue) {
		this.colValue = colValue;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "category_id")	
	public OsiCategories getOsiCategory() {
		return osiCategory;
	}

	public void setOsiCategory(OsiCategories osiCategory) {
		this.osiCategory = osiCategory;
	}

	



	

	@Column(name = "column_type", nullable = false, length = 0)
	
	public String getColType() {
		return colType;
	}

	public void setColType(String colType) {
		this.colType = colType;
	}




	@Column(name = "seq", nullable = false, length = 0)
	public Integer getSeq() {
		return seq;
	}

	public void setSeq(Integer seq) {
		this.seq = seq;
	}
	
	@Column(name = "column_source_type", nullable = false, length = 0)

	public String getColSrcType() {
		return colSrcType;
	}



	public void setColSrcType(String colSrcType) {
		this.colSrcType = colSrcType;
	}
	@Column(name = "column_source", nullable = false, length = 0)
	public String getColSrc() {
		return colSrc;
	}



	public void setColSrc(String colSrc) {
		this.colSrc = colSrc;
	}




	@Column(name = "is_mandatory", nullable = false, length = 0)
	public Integer getNullable() {
		return nullable;
	}



	public void setNullable(Integer nullable) {
		this.nullable = nullable;
	}

	@Column(name = "javascript_validation", nullable = false, length = 0)
	public String getSrcpValid() {
		return srcpValid;
	}



	public void setSrcpValid(String srcpValid) {
		this.srcpValid = srcpValid;
	}



	
	
}
