package com.osi.ems.domain;
// Generated Oct 10, 2017 12:00:12 PM by Hibernate Tools 5.2.3.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * OsiCurrencies generated by hbm2java
 */
@Entity
@Table(name = "osi_currencies")
public class OsiCurrencies implements java.io.Serializable {

	private Integer currencyId;
	private String currencyName;
	private String currencyCode;
	private Integer active;
	private Integer createdBy;
	private Date createdDate;
	private Integer updatedBy;
	private Date lastUpdateDate;
	private Set<OsiOrganizations> osiOrganizationsesForBaseCurrencyId = new HashSet<OsiOrganizations>(0);
	private Set<OsiOrganizations> osiOrganizationsesForReportingCurrencyId = new HashSet<OsiOrganizations>(0);
	//private Set<OsiJobCodes> osiJobCodeses = new HashSet<OsiJobCodes>(0);

	public OsiCurrencies() {
	}

	public OsiCurrencies(String currencyName, String currencyCode, Integer active, Integer createdBy, Date createdDate,
			Integer updatedBy, Date lastUpdateDate, Set<OsiOrganizations> osiOrganizationsesForBaseCurrencyId,
			Set<OsiOrganizations> osiOrganizationsesForReportingCurrencyId/*, Set<OsiJobCodes> osiJobCodeses*/) {
		this.currencyName = currencyName;
		this.currencyCode = currencyCode;
		this.active = active;
		this.createdBy = createdBy;
		this.createdDate = createdDate;
		this.updatedBy = updatedBy;
		this.lastUpdateDate = lastUpdateDate;
		this.osiOrganizationsesForBaseCurrencyId = osiOrganizationsesForBaseCurrencyId;
		this.osiOrganizationsesForReportingCurrencyId = osiOrganizationsesForReportingCurrencyId;
		//this.osiJobCodeses = osiJobCodeses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "currency_id", unique = true, nullable = false)
	public Integer getCurrencyId() {
		return this.currencyId;
	}

	public void setCurrencyId(Integer currencyId) {
		this.currencyId = currencyId;
	}

	@Column(name = "currency_name", length = 100)
	public String getCurrencyName() {
		return this.currencyName;
	}

	public void setCurrencyName(String currencyName) {
		this.currencyName = currencyName;
	}

	@Column(name = "currency_code", length = 20)
	public String getCurrencyCode() {
		return this.currencyCode;
	}

	public void setCurrencyCode(String currencyCode) {
		this.currencyCode = currencyCode;
	}

	@Column(name = "active")
	public Integer getActive() {
		return this.active;
	}

	public void setActive(Integer active) {
		this.active = active;
	}

	@Column(name = "created_by")
	public Integer getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(Integer createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "creation_date", length = 19)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Column(name = "last_updated_by")
	public Integer getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(Integer updatedBy) {
		this.updatedBy = updatedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "last_update_date", length = 19)
	public Date getLastUpdateDate() {
		return this.lastUpdateDate;
	}

	public void setLastUpdateDate(Date lastUpdateDate) {
		this.lastUpdateDate = lastUpdateDate;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "baseCurrencyId")
	public Set<OsiOrganizations> getOsiOrganizationsesForBaseCurrencyId() {
		return this.osiOrganizationsesForBaseCurrencyId;
	}

	public void setOsiOrganizationsesForBaseCurrencyId(Set<OsiOrganizations> osiOrganizationsesForBaseCurrencyId) {
		this.osiOrganizationsesForBaseCurrencyId = osiOrganizationsesForBaseCurrencyId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "reportingCurrencyId")
	public Set<OsiOrganizations> getOsiOrganizationsesForReportingCurrencyId() {
		return this.osiOrganizationsesForReportingCurrencyId;
	}

	public void setOsiOrganizationsesForReportingCurrencyId(
			Set<OsiOrganizations> osiOrganizationsesForReportingCurrencyId) {
		this.osiOrganizationsesForReportingCurrencyId = osiOrganizationsesForReportingCurrencyId;
	}

	/*@OneToMany(fetch = FetchType.LAZY, mappedBy = "osiCurrencies")
	public Set<OsiJobCodes> getOsiJobCodeses() {
		return this.osiJobCodeses;
	}

	public void setOsiJobCodeses(Set<OsiJobCodes> osiJobCodeses) {
		this.osiJobCodeses = osiJobCodeses;
	}*/

}
