package com.osi.ems.domain;
//Generated Dec 8, 2017 2:18:30 PM by Hibernate Tools 5.2.3.Final

import java.math.BigDecimal;
import java.util.Date;

/**
* OsiCostCenter generated by hbm2java
*/
public class OsiDeptGradesHistoryDTO implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private Integer deptGradeId;
	private Integer orgId;
	private Integer deptId;
	private Integer gradeId;
	private BigDecimal costPerHour;
	private BigDecimal costPerMonth;
	private Integer createdBy;
	private Date creationDate;
	private Integer lastUpdatedBy;
	private Date lastUpdateDate;
	private Integer internalCostOverheadPct;

	public OsiDeptGradesHistoryDTO() {
	}

	public Integer getDeptGradeId() {
		return deptGradeId;
	}

	public void setDeptGradeId(Integer deptGradeId) {
		this.deptGradeId = deptGradeId;
	}
	
	public Integer getDeptId() {
		return this.deptId;
	}

	public void setDeptId(Integer deptId) {
		this.deptId = deptId;
	}
	
	public Integer getOrgId() {
		return orgId;
	}

	public void setOrgId(Integer orgId) {
		this.orgId = orgId;
	}

	public Integer getGradeId() {
		return gradeId;
	}

	public void setGradeId(Integer gradeId) {
		this.gradeId = gradeId;
	}

	public BigDecimal getCostPerHour() {
		return costPerHour;
	}

	public void setCostPerHour(BigDecimal costPerHour) {
		this.costPerHour = costPerHour;
	}

	public BigDecimal getCostPerMonth() {
		return costPerMonth;
	}

	public void setCostPerMonth(BigDecimal costPerMonth) {
		this.costPerMonth = costPerMonth;
	}
	
	public Integer getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(Integer createdBy) {
		this.createdBy = createdBy;
	}

	public Date getCreationDate() {
		return this.creationDate;
	}

	public void setCreationDate(Date creationDate) {
		this.creationDate = creationDate;
	}

	public Integer getLastUpdatedBy() {
		return this.lastUpdatedBy;
	}

	public void setLastUpdatedBy(Integer lastUpdatedBy) {
		this.lastUpdatedBy = lastUpdatedBy;
	}

	public Date getLastUpdateDate() {
		return this.lastUpdateDate;
	}

	public void setLastUpdateDate(Date lastUpdateDate) {
		this.lastUpdateDate = lastUpdateDate;
	}

	public Integer getInternalCostOverheadPct() {
		return internalCostOverheadPct;
	}

	public void setInternalCostOverheadPct(Integer internalCostOverheadPct) {
		this.internalCostOverheadPct = internalCostOverheadPct;
	}
}
