package com.osi.ems.domain;
// Generated Dec 4, 2017 5:04:37 PM by Hibernate Tools 5.2.3.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * OsiTitles generated by hbm2java
 */
@Entity
@Table(name = "osi_titles")
public class OsiTitles implements java.io.Serializable {

	private String titleShortName;
	private Integer titleId;
	private String titleLongName;
	private String titleCode;
	private Integer createdBy;
	private Date creationDate;
	private Integer lastUpdatedBy;
	private Date lastUpdateDate;
	

	public OsiTitles() {
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	
	@Column(name = "TITLE_ID", unique = true, nullable = false)
	public Integer getTitleId() {
		return this.titleId;
	}

	public void setTitleId(Integer titleId) {
		this.titleId = titleId;
	}

	@Column(name = "TITLE_SHORT_NAME", unique = true, nullable = false, length = 45)
	public String getTitleShortName() {
		return this.titleShortName;
	}

	public void setTitleShortName(String titleShortName) {
		this.titleShortName = titleShortName;
	}

	@Column(name = "TITLE_LONG_NAME", length = 512)
	public String getTitleLongName() {
		return this.titleLongName;
	}

	public void setTitleLongName(String titleLongName) {
		this.titleLongName = titleLongName;
	}

	@Column(name = "TITLE_CODE", unique = true, nullable = false, length = 45)
	public String getTitleCode() {
		return this.titleCode;
	}

	public void setTitleCode(String titleCode) {
		this.titleCode = titleCode;
	}

	@Column(name = "CREATED_BY", nullable = false,updatable = false)
	public Integer getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(Integer createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATION_DATE", nullable = false, length = 19,updatable = false)
	public Date getCreationDate() {
		return this.creationDate;
	}

	public void setCreationDate(Date creationDate) {
		this.creationDate = creationDate;
	}

	@Column(name = "LAST_UPDATED_BY", nullable = false)
	public Integer getLastUpdatedBy() {
		return this.lastUpdatedBy;
	}

	public void setLastUpdatedBy(Integer lastUpdatedBy) {
		this.lastUpdatedBy = lastUpdatedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LAST_UPDATE_DATE", nullable = false, length = 19)
	public Date getLastUpdateDate() {
		return this.lastUpdateDate;
	}

	public void setLastUpdateDate(Date lastUpdateDate) {
		this.lastUpdateDate = lastUpdateDate;
	}



}
