package com.osi.urm.service.dto;

// Generated Mar 3, 2017 8:07:44 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * OsiLists generated by hbm2java
 */
public class OsiListsDTO implements java.io.Serializable {

	private int listId;
	private String listName;
	private String listDescription;
	private String validationType;
	private String listDataType;
	private Integer listDataMaxSize;
	private Integer createdBy;
	private Date creationDate;
	private Integer lastUpdatedBy;
	private Date lastUpdateDate;
	private String dateFormat;

	public OsiListsDTO() {
	}

	public OsiListsDTO(int listId) {
		this.listId = listId;
	}

	public OsiListsDTO(int listId, String listName, String listDescription,
			String validationType, String listDataType,
			Integer listDataMaxSize, Integer createdBy, Date creationDate,
			Integer lastUpdatedBy, Date lastUpdateDate, String dateFormat) {
		this.listId = listId;
		this.listName = listName;
		this.listDescription = listDescription;
		this.validationType = validationType;
		this.listDataType = listDataType;
		this.listDataMaxSize = listDataMaxSize;
		this.createdBy = createdBy;
		this.creationDate = creationDate;
		this.lastUpdatedBy = lastUpdatedBy;
		this.lastUpdateDate = lastUpdateDate;
		this.dateFormat = dateFormat;
	}

	public int getListId() {
		return this.listId;
	}

	public void setListId(int listId) {
		this.listId = listId;
	}

	public String getListName() {
		return this.listName;
	}

	public void setListName(String listName) {
		this.listName = listName;
	}

	public String getListDescription() {
		return this.listDescription;
	}

	public void setListDescription(String listDescription) {
		this.listDescription = listDescription;
	}

	public String getValidationType() {
		return this.validationType;
	}

	public void setValidationType(String validationType) {
		this.validationType = validationType;
	}

	public String getListDataType() {
		return this.listDataType;
	}

	public void setListDataType(String listDataType) {
		this.listDataType = listDataType;
	}

	public Integer getListDataMaxSize() {
		return this.listDataMaxSize;
	}

	public void setListDataMaxSize(Integer listDataMaxSize) {
		this.listDataMaxSize = listDataMaxSize;
	}

	public Integer getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(Integer createdBy) {
		this.createdBy = createdBy;
	}

	public Date getCreationDate() {
		return this.creationDate;
	}

	public void setCreationDate(Date creationDate) {
		this.creationDate = creationDate;
	}

	public Integer getLastUpdatedBy() {
		return this.lastUpdatedBy;
	}

	public void setLastUpdatedBy(Integer lastUpdatedBy) {
		this.lastUpdatedBy = lastUpdatedBy;
	}

	public Date getLastUpdateDate() {
		return this.lastUpdateDate;
	}

	public void setLastUpdateDate(Date lastUpdateDate) {
		this.lastUpdateDate = lastUpdateDate;
	}

	public String getDateFormat() {
		return this.dateFormat;
	}

	public void setDateFormat(String dateFormat) {
		this.dateFormat = dateFormat;
	}

}
