package com.osi.urm.service.dto;

// Generated Mar 3, 2017 8:07:44 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import com.fasterxml.jackson.annotation.JsonInclude;

/**
 * OsiReports generated by hbm2java
 */
@JsonInclude(JsonInclude.Include.NON_EMPTY)
public class OsiReportsDTO implements java.io.Serializable {

	private int reportId;
	private String reportName;
	private String userReportName;
	private String srcFileName;
	private Integer createdBy;
	private Date creationDate;
	private Integer lastUpdatedBy;
	private Date lastUpdateDate;
	private String reportType;
	private String outputType;
	private String selectedValues;
	private String childParameter;
	private Integer businessGroupId;
	private Set<OsiRptGrpRptsDTO> osiRptGrpRpts = new HashSet<OsiRptGrpRptsDTO>(0);

	public OsiReportsDTO() {
	}

	public OsiReportsDTO(int reportId) {
		this.reportId = reportId;
	}

	public OsiReportsDTO(int reportId, String reportName, String userReportName,
			String srcFileName, Integer createdBy, Date creationDate,
			Integer lastUpdatedBy, Date lastUpdateDate, String reportType,
			String outputType) {
		this.reportId = reportId;
		this.reportName = reportName;
		this.userReportName = userReportName;
		this.srcFileName = srcFileName;
		this.createdBy = createdBy;
		this.creationDate = creationDate;
		this.lastUpdatedBy = lastUpdatedBy;
		this.lastUpdateDate = lastUpdateDate;
		this.reportType = reportType;
		this.outputType = outputType;
	}

	public int getReportId() {
		return this.reportId;
	}

	public void setReportId(int reportId) {
		this.reportId = reportId;
	}

	public String getReportName() {
		return this.reportName;
	}

	public void setReportName(String reportName) {
		this.reportName = reportName;
	}

	public String getUserReportName() {
		return this.userReportName;
	}

	public void setUserReportName(String userReportName) {
		this.userReportName = userReportName;
	}

	public String getSrcFileName() {
		return this.srcFileName;
	}

	public void setSrcFileName(String srcFileName) {
		this.srcFileName = srcFileName;
	}

	public Integer getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(Integer createdBy) {
		this.createdBy = createdBy;
	}

	public Date getCreationDate() {
		return this.creationDate;
	}

	public void setCreationDate(Date creationDate) {
		this.creationDate = creationDate;
	}

	public Integer getLastUpdatedBy() {
		return this.lastUpdatedBy;
	}

	public void setLastUpdatedBy(Integer lastUpdatedBy) {
		this.lastUpdatedBy = lastUpdatedBy;
	}

	public Date getLastUpdateDate() {
		return this.lastUpdateDate;
	}

	public void setLastUpdateDate(Date lastUpdateDate) {
		this.lastUpdateDate = lastUpdateDate;
	}

	public String getReportType() {
		return this.reportType;
	}

	public void setReportType(String reportType) {
		this.reportType = reportType;
	}

	public String getOutputType() {
		return this.outputType;
	}

	public void setOutputType(String outputType) {
		this.outputType = outputType;
	}

	public String getSelectedValues() {
		return selectedValues;
	}

	public void setSelectedValues(String selectedValues) {
		this.selectedValues = selectedValues;
	}

	public String getChildParameter() {
		return childParameter;
	}

	public void setChildParameter(String childParameter) {
		this.childParameter = childParameter;
	}

	public Integer getBusinessGroupId() {
		return businessGroupId;
	}

	public void setBusinessGroupId(Integer businessGroupId) {
		this.businessGroupId = businessGroupId;
	}

	public Set<OsiRptGrpRptsDTO> getOsiRptGrpRpts() {
		return osiRptGrpRpts;
	}

	public void setOsiRptGrpRpts(Set<OsiRptGrpRptsDTO> osiRptGrpRpts) {
		this.osiRptGrpRpts = osiRptGrpRpts;
	}
}
