package com.osi.urm.service.dto;

import com.fasterxml.jackson.annotation.JsonInclude;

/**
 * OsiRptGrpRpts generated by hbm2java
 */
@JsonInclude(JsonInclude.Include.NON_EMPTY)
public class OsiRptGrpRptsDTO implements java.io.Serializable {

	private int rptGrpRptsId;
	private OsiReportsDTO osiReports;
	private OsiRptGroupsDTO osiRptGroups;
	private Integer businessGroupId;

	public int getRptGrpRptsId() {
		return rptGrpRptsId;
	}

	public OsiRptGrpRptsDTO(int rptGrpRptsId, OsiReportsDTO osiReports, OsiRptGroupsDTO osiRptGroups) {
		super();
		this.rptGrpRptsId = rptGrpRptsId;
		this.osiReports = osiReports;
		this.osiRptGroups = osiRptGroups;
	}

	public void setRptGrpRptsId(int rptGrpRptsId) {
		this.rptGrpRptsId = rptGrpRptsId;
	}

	public OsiReportsDTO getOsiReports() {
		return osiReports;
	}

	public void setOsiReports(OsiReportsDTO osiReports) {
		this.osiReports = osiReports;
	}

	public OsiRptGroupsDTO getOsiRptGroups() {
		return osiRptGroups;
	}

	public void setOsiRptGroups(OsiRptGroupsDTO osiRptGroups) {
		this.osiRptGroups = osiRptGroups;
	}

	public OsiRptGrpRptsDTO() {
	}

	public OsiRptGrpRptsDTO(int rptGrpRptsId) {
		this.rptGrpRptsId = rptGrpRptsId;
	}

	public Integer getBusinessGroupId() {
		return businessGroupId;
	}

	public void setBusinessGroupId(Integer businessGroupId) {
		this.businessGroupId = businessGroupId;
	}

}
