package com.osi.urm.service.dto;

// Generated Mar 3, 2017 8:07:44 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * OsiReportArgs generated by hbm2java
 */
public class OsiReportArgsDTO implements java.io.Serializable {

	private int reportArgsId;
	private Integer reportId;
	private Integer displaySeq;
	private String screenDisplayName;
	private String parameterName;
	private Integer listId;
	private String paramRequired;
	private String multiSelect;
	private Integer createdBy;
	private Date creationDate;
	private Integer lastUpdatedBy;
	private Date lastUpdateDate;

	public OsiReportArgsDTO() {
	}

	public OsiReportArgsDTO(int reportArgsId) {
		this.reportArgsId = reportArgsId;
	}

	public OsiReportArgsDTO(int reportArgsId, Integer reportId,
			Integer displaySeq, String screenDisplayName, String parameterName,
			Integer listId, String paramRequired, String multiSelect,
			Integer createdBy, Date creationDate, Integer lastUpdatedBy,
			Date lastUpdateDate) {
		this.reportArgsId = reportArgsId;
		this.reportId = reportId;
		this.displaySeq = displaySeq;
		this.screenDisplayName = screenDisplayName;
		this.parameterName = parameterName;
		this.listId = listId;
		this.paramRequired = paramRequired;
		this.multiSelect = multiSelect;
		this.createdBy = createdBy;
		this.creationDate = creationDate;
		this.lastUpdatedBy = lastUpdatedBy;
		this.lastUpdateDate = lastUpdateDate;
	}

	public int getReportArgsId() {
		return this.reportArgsId;
	}

	public void setReportArgsId(int reportArgsId) {
		this.reportArgsId = reportArgsId;
	}

	public Integer getReportId() {
		return this.reportId;
	}

	public void setReportId(Integer reportId) {
		this.reportId = reportId;
	}

	public Integer getDisplaySeq() {
		return this.displaySeq;
	}

	public void setDisplaySeq(Integer displaySeq) {
		this.displaySeq = displaySeq;
	}

	public String getScreenDisplayName() {
		return this.screenDisplayName;
	}

	public void setScreenDisplayName(String screenDisplayName) {
		this.screenDisplayName = screenDisplayName;
	}

	public String getParameterName() {
		return this.parameterName;
	}

	public void setParameterName(String parameterName) {
		this.parameterName = parameterName;
	}

	public Integer getListId() {
		return this.listId;
	}

	public void setListId(Integer listId) {
		this.listId = listId;
	}

	public String getParamRequired() {
		return this.paramRequired;
	}

	public void setParamRequired(String paramRequired) {
		this.paramRequired = paramRequired;
	}

	public String getMultiSelect() {
		return this.multiSelect;
	}

	public void setMultiSelect(String multiSelect) {
		this.multiSelect = multiSelect;
	}

	public Integer getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(Integer createdBy) {
		this.createdBy = createdBy;
	}

	public Date getCreationDate() {
		return this.creationDate;
	}

	public void setCreationDate(Date creationDate) {
		this.creationDate = creationDate;
	}

	public Integer getLastUpdatedBy() {
		return this.lastUpdatedBy;
	}

	public void setLastUpdatedBy(Integer lastUpdatedBy) {
		this.lastUpdatedBy = lastUpdatedBy;
	}

	public Date getLastUpdateDate() {
		return this.lastUpdateDate;
	}

	public void setLastUpdateDate(Date lastUpdateDate) {
		this.lastUpdateDate = lastUpdateDate;
	}

}
